name: after-midnight 
on:
  schedule:
    - cron: "29 1 * * *"
  workflow_dispatch:  
jobs: 
   messageWhatsApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Notification WhatsApp
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.WPP_TWILIO_ACCOUNT_SID }}
          auth_token: ${{ secrets.WPP_TWILIO_AUTH_TOKEN }}
          to_whatsapp_no: ${{ secrets.WPP_TWILIO_TO_WHATSAPP_NO }}
          message: "CI 👉🏻 Your message here"
        uses: khaled-ibtikar/whatsapp-push-notify-action@master    
    
    
