name: after-midnight 
on:
  schedule:
    - cron: "29 1 * * *"
jobs: 
  prep:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pywhatkit
    
    
